In [1]:
import numpy as np

# read in file
with open('calibration_values.txt') as f:
    lines = f.readlines()
print(lines)

['6798seven\n', 'six8b32csscsdgjsevenfivedlhzhc\n', 'fcvvkvjjnhfivesixfiveninesxlvnhfckc54\n', 'feightwo4twofivefour\n', 'cgpzm2sevenone68636\n', '498879\n', 'fivetwo2plltvdfourhhgrfn\n', 'onertxzlzdnxn2seven\n', 'ninethree4v1five\n', '5pnnss16lzbsmcckeightdseven\n', 'jthree249four2cjzqmmbrqnnine\n', 'foursixfourfbgvqm1rchdlmzhtzqqfjzpmln\n', 'twojtwoscbrtgmnqzvbfbzvrtkxhmf76nine\n', '2fourtwo\n', 'svxz8bjvt5zzvjzhkmtmnnft92\n', 'threetffnjvkfh81nineqqshzdf2vtjfqjtbdv\n', 'seven1drfivethreedpqflxgdshlzmmnrb\n', '7sggjxkcxfourthreefourtwos3nine\n', '39t6rvkbdnfpssj6djnfbqklkgfsqbf\n', '3four2zcfvtplkrbeight274\n', 'one7sixninesix\n', 'kkxmtmdthree6jrj6\n', '81sevenmnine1llbqrsprc\n', '5nine9qgjceight\n', 'three1sdmq9sevenfournine\n', 'khnlbmzhvlsix3\n', 'nineone6onesixvlnlxeightfive\n', 'schplznseveneightnlcxgr7four\n', '6one1djcdmpdrgq3two\n', 'fourzhpnphmq52r813four\n', 'scsxjthreefoureight2fivepfmpfj8\n', '69xvbxfffmr7one8gmch8\n', 'one8tfpgrdhm\n', '2gxmhtfrbrkpdvlvsmdqrktxtrpssbrv9

In [32]:
calibration_values = np.array([]);

# loop through lines and extract number of interest
for ii in lines:
    print(ii)
    this_number = np.array([]);
    for ch in range(len(ii)):
        #print(ii[ch])
        if ii[ch].isdigit():
            #print(int(ii[ch]))
            this_number = np.append(this_number,int(ii[ch]));
                
    #print(this_number);
    if len(this_number)>1:
        calibration_values = np.append(calibration_values,int(str(int(this_number[0]))+str(int(this_number[-1]))))
        print(calibration_values[-1])
    if len(this_number)==1:
        calibration_values = np.append(calibration_values,int(str(int(this_number[0]))+str(int(this_number[-1]))));

        
print(calibration_values)

6798seven

68.0
six8b32csscsdgjsevenfivedlhzhc

82.0
fcvvkvjjnhfivesixfiveninesxlvnhfckc54

54.0
feightwo4twofivefour

cgpzm2sevenone68636

26.0
498879

49.0
fivetwo2plltvdfourhhgrfn

onertxzlzdnxn2seven

ninethree4v1five

41.0
5pnnss16lzbsmcckeightdseven

56.0
jthree249four2cjzqmmbrqnnine

22.0
foursixfourfbgvqm1rchdlmzhtzqqfjzpmln

twojtwoscbrtgmnqzvbfbzvrtkxhmf76nine

76.0
2fourtwo

svxz8bjvt5zzvjzhkmtmnnft92

82.0
threetffnjvkfh81nineqqshzdf2vtjfqjtbdv

82.0
seven1drfivethreedpqflxgdshlzmmnrb

7sggjxkcxfourthreefourtwos3nine

73.0
39t6rvkbdnfpssj6djnfbqklkgfsqbf

36.0
3four2zcfvtplkrbeight274

34.0
one7sixninesix

kkxmtmdthree6jrj6

66.0
81sevenmnine1llbqrsprc

81.0
5nine9qgjceight

59.0
three1sdmq9sevenfournine

19.0
khnlbmzhvlsix3

nineone6onesixvlnlxeightfive

schplznseveneightnlcxgr7four

6one1djcdmpdrgq3two

63.0
fourzhpnphmq52r813four

53.0
scsxjthreefoureight2fivepfmpfj8

28.0
69xvbxfffmr7one8gmch8

68.0
one8tfpgrdhm

2gxmhtfrbrkpdvlvsmdqrktxtrpssbrv933

23.0
4vfrtkdqlbtword

In [33]:
# add up calibration values to get to solution
solution = np.sum(calibration_values);
print(solution)

54239.0


In [34]:
# Part 2!
def locations_of_substring(string, substring):
    """Return a list of locations of a substring."""

    substring_length = len(substring)    
    def recurse(locations_found, start):
        location = string.find(substring, start)
        if location != -1:
            return recurse(locations_found + [location], location+substring_length)
        else:
            return locations_found

    return recurse([], 0)

calibration_values = np.array([]);

# loop through lines and extract number of interest
for jj in lines:
    
    # replace written digits with numbers (have to read from left to right)
    s_ = jj;
    
    find_1 = locations_of_substring(s_,'one'); 
    find_2 = locations_of_substring(s_,'two');
    find_3 = locations_of_substring(s_,'three');
    find_4 = locations_of_substring(s_,'four');
    find_5 = locations_of_substring(s_,'five');
    find_6 = locations_of_substring(s_,'six');
    find_7 = locations_of_substring(s_,'seven');
    find_8 = locations_of_substring(s_,'eight');
    find_9 = locations_of_substring(s_,'nine');
    
    
    if len(find_1) > 0: 
        for ii in find_1: 
            s_=s_[:ii+1]+'1'+s_[ii+2:];
    if len(find_2) > 0: 
        for ii in find_2: 
            s_=s_[:ii+1]+'2'+s_[ii+2:];
    if len(find_3) > 0: 
        for ii in find_3: 
            s_=s_[:ii+1]+'3'+s_[ii+2:];
    if len(find_4) > 0: 
        for ii in find_4: 
            s_=s_[:ii+1]+'4'+s_[ii+2:];
    if len(find_5) > 0: 
        for ii in find_5: 
            s_=s_[:ii+1]+'5'+s_[ii+2:];
    if len(find_6) > 0: 
        for ii in find_6: 
            s_=s_[:ii+1]+'6'+s_[ii+2:];
    if len(find_7) > 0: 
        for ii in find_7: 
            s_=s_[:ii+1]+'7'+s_[ii+2:];
    if len(find_8) > 0: 
        for ii in find_8: 
            s_=s_[:ii+1]+'8'+s_[ii+2:];
    if len(find_9) > 0: 
        for ii in find_9: 
            s_=s_[:ii+1]+'9'+s_[ii+2:];
    
    
    print(jj)
    print(s_)
    this_number = np.array([]);
    for ch in range(len(s_)):
        #print(ii[ch])
        if s_[ch].isdigit():
            #print(int(ii[ch]))
            this_number = np.append(this_number,int(s_[ch]));
                
    print(this_number);
    if len(this_number)>1:
        calibration_values = np.append(calibration_values,int(str(int(this_number[0]))+str(int(this_number[-1]))))
        print(calibration_values[-1])
    if len(this_number)==1:
        calibration_values = np.append(calibration_values,int(str(int(this_number[0]))+str(int(this_number[-1]))));
        print(calibration_values[-1])
        
# add up calibration values to get to solution
new_solution = np.sum(calibration_values);
print(new_solution)

6798seven

6798s7ven

[6. 7. 9. 8. 7.]
67.0
six8b32csscsdgjsevenfivedlhzhc

s6x8b32csscsdgjs7venf5vedlhzhc

[6. 8. 3. 2. 7. 5.]
65.0
fcvvkvjjnhfivesixfiveninesxlvnhfckc54

fcvvkvjjnhf5ves6xf5ven9nesxlvnhfckc54

[5. 6. 5. 9. 5. 4.]
54.0
feightwo4twofivefour

fe8ght2o4t2of5vef4ur

[8. 2. 4. 2. 5. 4.]
84.0
cgpzm2sevenone68636

cgpzm2s7veno1e68636

[2. 7. 1. 6. 8. 6. 3. 6.]
26.0
498879

498879

[4. 9. 8. 8. 7. 9.]
49.0
fivetwo2plltvdfourhhgrfn

f5vet2o2plltvdf4urhhgrfn

[5. 2. 2. 4.]
54.0
onertxzlzdnxn2seven

o1ertxzlzdnxn2s7ven

[1. 2. 7.]
17.0
ninethree4v1five

n9net3ree4v1f5ve

[9. 3. 4. 1. 5.]
95.0
5pnnss16lzbsmcckeightdseven

5pnnss16lzbsmccke8ghtds7ven

[5. 1. 6. 8. 7.]
57.0
jthree249four2cjzqmmbrqnnine

jt3ree249f4ur2cjzqmmbrqnn9ne

[3. 2. 4. 9. 4. 2. 9.]
39.0
foursixfourfbgvqm1rchdlmzhtzqqfjzpmln

f4urs6xf4urfbgvqm1rchdlmzhtzqqfjzpmln

[4. 6. 4. 1.]
41.0
twojtwoscbrtgmnqzvbfbzvrtkxhmf76nine

t2ojt2oscbrtgmnqzvbfbzvrtkxhmf76n9ne

[2. 2. 7. 6. 9.]
29.0
2fourtwo

2f4urt2o

[2. 4. 2.]


7s6xtf

[7. 6.]
76.0
sixxhxkvgnbz3rbdnvgf

s6xxhxkvgnbz3rbdnvgf

[6. 3.]
63.0
ckq745ninepqk

ckq745n9nepqk

[7. 4. 5. 9.]
79.0
1snlkqn

1snlkqn

[1.]
11.0
ninetqvcllfvcfs62qtt6seven

n9netqvcllfvcfs62qtt6s7ven

[9. 6. 2. 6. 7.]
97.0
59khlmz

59khlmz

[5. 9.]
59.0
eightdndsvdcqneight9twonenf

e8ghtdndsvdcqne8ght9t2o1enf

[8. 8. 9. 2. 1.]
81.0
zgcnqqmlgsmfzqbkllvsknsevensix5

zgcnqqmlgsmfzqbkllvskns7vens6x5

[7. 6. 5.]
75.0
8qqxshjnnsp

8qqxshjnnsp

[8.]
88.0
xfvttdnxhz4sixsjkqhpfszn212three

xfvttdnxhz4s6xsjkqhpfszn212t3ree

[4. 6. 2. 1. 2. 3.]
43.0
fivelssnmckseven4ftqt

f5velssnmcks7ven4ftqt

[5. 7. 4.]
54.0
2qsqpjmcbtvxjgqhhk

2qsqpjmcbtvxjgqhhk

[2.]
22.0
tztwone749ninelncrmvthfourpgcbxzxvs

tzt2o1e749n9nelncrmvthf4urpgcbxzxvs

[2. 1. 7. 4. 9. 9. 4.]
24.0
4threecgnjpthnsgxhxbffour8eightsvmjkg5

4t3reecgnjpthnsgxhxbff4ur8e8ghtsvmjkg5

[4. 3. 4. 8. 8. 5.]
45.0
458sixseven6one1smkjk

458s6xs7ven6o1e1smkjk

[4. 5. 8. 6. 7. 6. 1. 1.]
41.0
seven4fourrgqffqthree7

s7ven4f4urrgqffqt3ree7

[